### ISSUE TITLE
Is it possible for sound to miss when all cogs in the battle are lured?

### ISSUE THREAD

**Issue by JonathanHelianthicusDoe** [QED1224/Toontown-Resources#10]
As written, all cogs being lured would just make `bonus` really large, but `atkAcc` is still bounded above by `95`, so sound on a row of all-lured cogs should (again, as written) have a 5% chance of missing.

However, anecdotally I don&rsquo;t think(?) that I&rsquo;ve ever seen sound miss in a case where all cogs are lured. Of course, intuitively, one would expect that this is not a common scenario anyways:

> Don't use sound on lured cogs.

But there are actually *four* cases (that I can think of off the top of my head) where this does happen:

* It&rsquo;s not uncommon for someone to use a throwaway lure gag (usually a blue magnet) to make sound less likely (or so we would hope!) to miss whenever the sound gag(s) that everyone else is using would kill the cogs anyways. This is especially common with:
    * Low-level cogs (factories, VPs, buildings&hellip;).
    * When there are 4 toons in battle and the highest cog level is 9.
    * When one toon is soundless.
* There are a lot of missing laff points, so one person lures with magnet/hypno while most everyone else toons up. Then, next round it is not uncommon to sound if appropriate.
* Someone is intentionally using sound on lured cogs to grief their &ldquo;teammates&rdquo;.
* There is only one cog left in battle and it has low HP. Then usually more-or-less everyone picks a different gag track to make it unlikely that **all** of their gags miss. In this case, seeing both sound and lure being used is not uncommon.

There seems to be a kind of folk consensus that sound cannot miss when targeting cogs that are all lured, and the prospect of it missing is a kind of boogeyman (again, in my experience). So I do wonder if my experience is correct, and the rules as written here are not.

**Comment by QED1224** [comment]
> Is it possible for sound to miss when all cogs in the battle are lured?

The answer is *yes*, but technically *no*: Sound can only miss on lured cogs if there is at least one unlured cog among the group. However, any cog that is defeated in the same round that it was lured is considered "unlured" until the round ends. This means that, visually speaking, Sound can in fact miss when all cogs are "lured."

---

That said, this doesn't mean that the given formula is "incorrect" (indeed, this is one of the easiest sections to verify for anyone who is even slightly familiar with Python); it simply doesn't apply when all cogs are lured. 

This could have been explained in the Special Cases section, but I think the basic mechanics of Lure were taken for granted (perhaps inadvertently) as common knowledge.

(You also won't, for example, find information on whether or not Drop will hit lured cogs as that, too, never came up as a topic of discussion.)

Ultimately, the goal of this project wasn't (and still isn't) to provide a comprehensive description of every aspect of Toontown -- general background information was only added when it was deemed relevant to a specific question.

**Comment by JonathanHelianthicusDoe** [comment]
> This could have been explained in the Special Cases section, but I think the basic mechanics of Lure were taken for granted (perhaps inadvertently) as common knowledge.

Right, so that&rsquo;s my whole point here: it shouldn&rsquo;t be taken for granted nor as common knowledge, as there are plenty of much more obvious things in this document that **are** explicitly given (hence the issue). So clearly it is not outside of the scope of this document.

> (You also won't, for example, find information on whether or not Drop will hit lured cogs as that, too, never came up as a topic of discussion.)

So, drop gags missing on lured cogs is particularly obvious because the game gives this to you explicitly in terms of visuals. Drop gags always visually hit the same spot (when they don&rsquo;t miss &mdash; or even when they do, in the case of level 3 or lower drop gags\*), but when cogs are lured, they visually move forwards. On the other hand, sound misses on lured cogs when at least one cog isn&rsquo;t lured, so there is no indication that sound couldn&rsquo;t miss on a row of all-lured cogs. Indeed, as you say, it can *visually* miss (when you actually *do* have an unlured cog, but it is dead). Altogether, the game gives basically no indication of whether or not sound can miss all-lured cogs, and even sends seemingly mixed messages. If this makes it &ldquo;common knowledge&rdquo; to you, then fine.

Even the problem of drop hitting lured cogs is complicated by drop gags that hit multiple cogs (Toontanic, drop SOSs).

> Ultimately, the goal of this project wasn't (and still isn't) to provide a comprehensive description of every aspect of Toontown -- general background information was only added when it was deemed relevant to a specific question.

I can see clearly from the document that this is the case &mdash; I&rsquo;ve played the game myself (starting in 2003), so I am aware of the mechanics that are not explained here explicitly. But this is not a trivial detail, and &ldquo;general background information&rdquo; is indeed relevant for this specific question, which is why I&rsquo;ve posed it here. My assumption is that the detailed information in this document is intended to clarify things that have no clear in-game indications *without* resorting to blind trust in a measly set of personal anecdotes.

---

\*Note that everyone&rsquo;s first experience with drop gags is with drop gags that are low level (specifically, 3 or lower). If you use such a drop gag on a cog and it misses, the cog has to dodge it. *However*, if the cog is lured, then the cog doesn&rsquo;t have to dodge the gag. This is what I mean by explicit visual cues (something that sound gags lack).

**Comment by tkoalas** [comment]
If the code is as-written, with the atkAcc capped at 95, then sound has a 5% chance to miss lured cogs. Am I missing something? The lure bonus appears to fall under the 95 cap, unless there is info missing from your write up. In the special cases, you only list fires and traps as being assigned an atkHit of 1, which would leave a row of fully lured cogs subject to the luredRatio. luredRatio may equal 100, as all the cogs are lured, but the atkAcc is capped at 95. Unless this document is incomplete, it appears as though sound can miss a fully lured set of cogs. In fact, it actually appears pointless to lure before using sound unless someone is not maxed on sound. In that case, you do lure to increase atkAcc to 95.
