### ISSUE TITLE
Active lure interactive prop

### ISSUE THREAD

**Issue by tkoalas** [QED1224/Toontown-Resources#11]
In the Attack Accuracy section, it says lure will use the AvLureBonusAccuracy when the lure is organic or when "there is an active Lure interactive prop". Looking through the text dumps listed, I see the log push out the text "using oragnic OR prop bonus lure accuracy" (yes, there is also a spelling error in organic, which I just found, too), but I only see this come up for organic lure and not when just a trap is used with an ordinary lure. So I guess my guess is, what is an "active lure interactive prop", and does it really affect the propAcc value outside of the bonus? From all the text dumps, it looks as though organic lure boosts the propAcc by 10, but trap boosts it by 20% either way (organic and non-organic). If the command followed as suggested, "using oragnic OR prop bonus lure accuracy", you should see a final percentage be 30% better in either scenario, as it should use theAvLureBonusAccuracy in either case. But as-is, it looks as though you see a 30% with org lure and trap and only a 20% boost with non-organic lure and trap. What am I missing or not understanding? 

I think the line about the "active lure interactive prop" should be removed or clarified. It doesn't seem to apply once you actually examine the code and its result.

**Comment by QED1224** [comment]
> So I guess my guess is, what is an "active lure interactive prop", and does it really affect the propAcc value outside of the bonus?

An "active lure interactive prop" refers to the bonus associated with animated street props (the Silly Meter related "power-ups" provided to certain gags). 

I believe in practice we only saw implementations for Squirt (fire hydrants), Toon-up (trashcans), and Throw (mailboxes), but the source code quite explicitly checks this for Lure too. So, as written, the guide is strictly correct: if there were an active lure interactive prop, it would indeed apply in this case.

(In fact, the "using oragnic OR prop bonus lure accuracy" string was one of the original  debugging messages left in the source code -- i.e., not one created by this project.)
