### ISSUE TITLE
Two+ gags of the same track on the same cog having possibly different hit/miss results no longer applies to TTR

### ISSUE THREAD

**Issue by JonathanHelianthicusDoe** [QED1224/Toontown-Resources#9]
> ## [Is it possible for two gags of the same track, aiming for the same cog, to have different hit/miss results?](https://github.com/QED1224/Toontown-Resources#misc-3)
>
> Yes, due to how toon attacks are ordered [&hellip;]

Compare [these release notes](https://toontownrewritten.com/news/item/493/toontowns-surprise-update) ([archived](https://web.archive.org/web/20191112013911/https://toontownrewritten.com/news/item/493/toontowns-surprise-update)):

> Gags of the same type against the same Cog will now either all miss or all hit in that round. This change does not impact the chances of a Gag track hitting one Cog and the same track missing another Cog.

See this duplicated [here](https://toontownrewritten.fandom.com/wiki/Release_Notes_(2018)#July_20.2C_2018_.5Bttr-live-v2.2.0.5D).

**Comment by QED1224** [comment]
I updated the "Notes" section to reflect these changes. I also intend to go through and add a link to the Notes section from any impacted section in the main guide.

> This change does not impact the chances of a Gag track hitting one Cog and the same track missing another Cog.

I'm not sure what they were trying to get at here -- it seems both quite obvious and entirely unrelated to the stated change.
